# this file ads an abstraction when we want to point to some table, we use the name from here instead hardcodeing it
version: 2
sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings # name we are going to use 
        identifier: raw_listings # name in the DB
      - name: hosts
        identifier: raw_hosts
      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
